"""Change field status -> verification_status in Saintpaulia

Revision ID: 042c0c2d37f1
Revises: c535da37ebbf
Create Date: 2025-08-13 14:19:46.906221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042c0c2d37f1'
down_revision: Union[str, None] = 'c535da37ebbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saintpaulia_varieties', sa.Column('verification_status', sa.Boolean(), nullable=True))
    op.drop_column('saintpaulia_varieties', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saintpaulia_varieties', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('saintpaulia_varieties', 'verification_status')
    # ### end Alembic commands ###
