"""Add is_verified field to Saintpaulia

Revision ID: 437069a9e2c6
Revises: 962cd4ac63be
Create Date: 2025-07-14 11:26:09.401563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437069a9e2c6'
down_revision: Union[str, None] = '962cd4ac63be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.add_column('saintpaulia_varieties', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_column('saintpaulia_varieties', 'is_verified')
    # ### end Alembic commands ###
