"""Add UploadedPhoto model

Revision ID: 4e744c574276
Revises: 2d75e06c8b05
Create Date: 2025-05-12 13:54:12.378532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e744c574276'
down_revision: Union[str, None] = '2d75e06c8b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saintpaulia_varieties', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saintpaulia_varieties', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
