"""Deleted Foreign keys for variety_id and variety_name for logs and photo tables

Revision ID: 87bb0638df77
Revises: bdf0552f2db5
Create Date: 2025-07-29 11:16:28.862275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87bb0638df77'
down_revision: Union[str, None] = 'bdf0552f2db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_constraint('photo_logs_variety_id_fkey', 'photo_logs', type_='foreignkey')
    op.alter_column('saintpaulia_logs', 'variety_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('saintpaulia_logs', 'variety_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('saintpaulia_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('saintpaulia_logs_variety_id_fkey', 'saintpaulia_logs', type_='foreignkey')
    op.drop_constraint('saintpaulia_varieties_verified_by_fkey', 'saintpaulia_varieties', type_='foreignkey')
    op.create_foreign_key(None, 'saintpaulia_varieties', 'users', ['verified_by'], ['id'], ondelete='SET NULL')
    op.alter_column('uploaded_photos', 'variety_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uploaded_photos_variety_id_fkey', 'uploaded_photos', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.create_foreign_key('uploaded_photos_variety_id_fkey', 'uploaded_photos', 'saintpaulia_varieties', ['variety_id'], ['id'])
    op.alter_column('uploaded_photos', 'variety_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'saintpaulia_varieties', type_='foreignkey')
    op.create_foreign_key('saintpaulia_varieties_verified_by_fkey', 'saintpaulia_varieties', 'users', ['verified_by'], ['id'])
    op.create_foreign_key('saintpaulia_logs_variety_id_fkey', 'saintpaulia_logs', 'saintpaulia_varieties', ['variety_id'], ['id'])
    op.alter_column('saintpaulia_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('saintpaulia_logs', 'variety_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('saintpaulia_logs', 'variety_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('photo_logs_variety_id_fkey', 'photo_logs', 'saintpaulia_varieties', ['variety_id'], ['id'])
    # ### end Alembic commands ###
