"""Add new fields to Saintpaulia

Revision ID: 87bff2132701
Revises: dcac9504db92
Create Date: 2025-08-13 13:18:06.607021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87bff2132701'
down_revision: Union[str, None] = 'dcac9504db92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saintpaulia_varieties', sa.Column('growth_type', sa.String(), nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('main_flower_color', sa.String(), nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('flower_color_type', sa.String(), nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('flower_edge_color', sa.String(), nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('flower_colors_all', sa.Text(), nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('petals_shape', sa.String(), nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('leaf_color_type', sa.String(), nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('leaf_features', sa.Text(), nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('breeder', sa.String(), nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('breeder_origin_country', sa.String(), nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('data_source', sa.String(), nullable=True))
    op.alter_column('saintpaulia_varieties', 'ruffles',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('saintpaulia_varieties', 'selectionist')
    op.drop_column('saintpaulia_varieties', 'flower_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saintpaulia_varieties', sa.Column('flower_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('selectionist', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('saintpaulia_varieties', 'ruffles',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_column('saintpaulia_varieties', 'data_source')
    op.drop_column('saintpaulia_varieties', 'breeder_origin_country')
    op.drop_column('saintpaulia_varieties', 'breeder')
    op.drop_column('saintpaulia_varieties', 'leaf_features')
    op.drop_column('saintpaulia_varieties', 'leaf_color_type')
    op.drop_column('saintpaulia_varieties', 'petals_shape')
    op.drop_column('saintpaulia_varieties', 'flower_colors_all')
    op.drop_column('saintpaulia_varieties', 'flower_edge_color')
    op.drop_column('saintpaulia_varieties', 'flower_color_type')
    op.drop_column('saintpaulia_varieties', 'main_flower_color')
    op.drop_column('saintpaulia_varieties', 'growth_type')
    # ### end Alembic commands ###
