"""User changed, UserRoleHistory added

Revision ID: a8c50f7cc721
Revises: fe706f57d29b
Create Date: 2025-09-18 16:47:09.485515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c50f7cc721'
down_revision: Union[str, None] = 'fe706f57d29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old_role', sa.Enum('user', 'expert', 'breeder', 'admin', 'superadmin', name='userrole_history_old'), nullable=True),
    sa.Column('new_role', sa.Enum('user', 'expert', 'breeder', 'admin', 'superadmin', name='userrole_history_new'), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_history_user_id'), 'user_role_history', ['user_id'], unique=False)
    op.add_column('users', sa.Column('user_creation_date', sa.DateTime(), nullable=True, server_default=sa.text('now()')))
    op.add_column('users', sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'email_confirmed_at')
    op.drop_column('users', 'user_creation_date')
    op.drop_index(op.f('ix_user_role_history_user_id'), table_name='user_role_history')
    op.drop_table('user_role_history')
    # ### end Alembic commands ###
