"""Source of photos added to Saintpaulia

Revision ID: b6cf5ea83d0c
Revises: f8d3ea50af83
Create Date: 2025-08-19 16:55:06.376757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6cf5ea83d0c'
down_revision: Union[str, None] = 'f8d3ea50af83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saintpaulia_varieties', sa.Column('photo_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saintpaulia_varieties', 'photo_source')
    # ### end Alembic commands ###
