"""Edit saintpaulia_logs table

Revision ID: bdf0552f2db5
Revises: 3274c3cf5e61
Create Date: 2025-07-18 15:09:05.325462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf0552f2db5'
down_revision: Union[str, None] = '3274c3cf5e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saintpaulia_logs', sa.Column('variety_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'saintpaulia_logs', 'saintpaulia_varieties', ['variety_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saintpaulia_logs', type_='foreignkey')
    op.drop_column('saintpaulia_logs', 'variety_id')
    # ### end Alembic commands ###
