"""Add Verification classes to Saintpaulia

Revision ID: beaf157b5c73
Revises: 437069a9e2c6
Create Date: 2025-07-15 15:38:57.735469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beaf157b5c73'
down_revision: Union[str, None] = '437069a9e2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.add_column('saintpaulia_varieties', sa.Column('verification_note', sa.Text(), nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('verification_date', sa.DateTime(), nullable=True))
    op.alter_column('saintpaulia_varieties', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'saintpaulia_varieties', 'users', ['verified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_constraint(None, 'saintpaulia_varieties', type_='foreignkey')
    op.alter_column('saintpaulia_varieties', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('saintpaulia_varieties', 'verification_date')
    op.drop_column('saintpaulia_varieties', 'verified_by')
    op.drop_column('saintpaulia_varieties', 'verification_note')
    # ### end Alembic commands ###
