"""Change field is_verified -> status in Saintpaulia

Revision ID: c535da37ebbf
Revises: 87bff2132701
Create Date: 2025-08-13 14:01:05.599317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c535da37ebbf'
down_revision: Union[str, None] = '87bff2132701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saintpaulia_varieties', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('saintpaulia_varieties', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saintpaulia_varieties', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('saintpaulia_varieties', 'status')
    # ### end Alembic commands ###
