"""Upd model for Saintpaulia

Revision ID: c709d0c22883
Revises: ddf687689fca
Create Date: 2025-04-23 16:22:25.291781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c709d0c22883'
down_revision: Union[str, None] = 'ddf687689fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saintpaulia_varieties', 'flower_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('saintpaulia_varieties', 'flower_size',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('saintpaulia_varieties', 'flower_doubleness',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('saintpaulia_varieties', 'selectionist',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saintpaulia_varieties', 'selectionist',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('saintpaulia_varieties', 'flower_doubleness',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('saintpaulia_varieties', 'flower_size',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('saintpaulia_varieties', 'flower_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
