"""Initial clean state with all models

Revision ID: ccfaaf59a918
Revises: 
Create Date: 2025-06-30 15:52:56.564598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfaaf59a918'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saintpaulia_varieties', sa.Column('ruffles', sa.Boolean(), nullable=True))
    op.add_column('saintpaulia_varieties', sa.Column('ruffles_color', sa.String(), nullable=True))
    op.alter_column(
        'users',
        'refresh_token',
        existing_type=sa.String(length=255),
        type_=sa.String(length=512),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saintpaulia_varieties', 'ruffles_color')
    op.drop_column('saintpaulia_varieties', 'ruffles')
    op.alter_column(
        'users',
        'refresh_token',
        existing_type=sa.String(length=512),
        type_=sa.String(length=255),
        existing_nullable=True
    )
    # ### end Alembic commands ###
