"""Initial model for Saintpaulia

Revision ID: ddf687689fca
Revises: f8c92bf5bb72
Create Date: 2025-04-22 16:43:16.431488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf687689fca'
down_revision: Union[str, None] = 'f8c92bf5bb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saintpaulia_varieties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size_category', sa.String(), nullable=False),
    sa.Column('flower_color', sa.String(), nullable=True),
    sa.Column('flower_size', sa.String(), nullable=True),
    sa.Column('flower_shape', sa.String(), nullable=True),
    sa.Column('flower_doubleness', sa.String(), nullable=True),
    sa.Column('leaf_shape', sa.String(), nullable=True),
    sa.Column('leaf_variegation', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('selectionist', sa.String(), nullable=True),
    sa.Column('selection_year', sa.Integer(), nullable=True),
    sa.Column('blooming_features', sa.Text(), nullable=True),
    sa.Column('record_author', sa.String(), nullable=True),
    sa.Column('record_creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_saintpaulia_varieties_id'), 'saintpaulia_varieties', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saintpaulia_varieties_id'), table_name='saintpaulia_varieties')
    op.drop_table('saintpaulia_varieties')
    # ### end Alembic commands ###
