"""Upd-2 model for Saintpaulia

Revision ID: f0f236a51d88
Revises: c709d0c22883
Create Date: 2025-04-23 17:39:45.999886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f236a51d88'
down_revision: Union[str, None] = 'c709d0c22883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saintpaulia_varieties', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'saintpaulia_varieties', 'users', ['owner_id'], ['id'])
    op.drop_column('saintpaulia_varieties', 'record_author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saintpaulia_varieties', sa.Column('record_author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'saintpaulia_varieties', type_='foreignkey')
    op.drop_column('saintpaulia_varieties', 'owner_id')
    # ### end Alembic commands ###
