"""PhotoLog upd

Revision ID: fe706f57d29b
Revises: b6cf5ea83d0c
Create Date: 2025-09-08 15:56:38.687461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe706f57d29b'
down_revision: Union[str, None] = 'b6cf5ea83d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('photo_logs_photo_id_fkey', 'photo_logs', type_='foreignkey')
    op.create_foreign_key(None, 'photo_logs', 'uploaded_photos', ['photo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo_logs', type_='foreignkey')
    op.create_foreign_key('photo_logs_photo_id_fkey', 'photo_logs', 'uploaded_photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###
